branch-defaults:
  feature/expanded-storage:
    environment: null
    group_suffix: null
  master:
    environment: geth-mainnet-node-prod
  staging:
    environment: geth-mainnet-node-staging
global:
  application_name: geth-mainnet-node
  artifact: deploy.zip
  branch: master
  default_region: us-east-1
  repository: null
  sc: git
